import openapiTS, { astToString } from 'openapi-typescript'

const HEADER = `/* eslint-disable */
// GENERATED by scripts/generate.mjs from openapi.json (Distru's published spec) after the
// nullability patch in src/patch.ts. Do not edit by hand; run \`pnpm gen\` in this package.
`

/** patchNullable is passed in so the test can use src/patch.ts and the CLI dist/patch.js. */
export async function generateTypes(rawSpec, patchNullable) {
  const { spec } = patchNullable(rawSpec)
  const ast = await openapiTS(spec, { alphabetize: true })
  return HEADER + astToString(ast)
}
